
name: Build and test ShoppingList app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_run_unit_tests:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run the app
      run: npm start &
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "VaninaDimitrova"

  run_ui_tests:

    needs: build_run_unit_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start app
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui
  
  deploy_production:

    needs: run_ui_tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app to production 
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} 
          api-key: ${{ secrets.RENDER_API_KEY }}